#Network Manager Ghost Configuration

[device]
#Randomize mac during wifi scanning
wifi.scan-rand-mac-address=yes

[connection]
#Randomize mac for every ethernet connection
ethernet.cloned-mac-address=random

#Randomize mac for every wifi connection
wifi.cloned-mac-address=random

#Prevent hostname being sent
ipv4.dhcp-send-hostname=0
ipv6.dhcp-send-hostname=0

#Enable ipv6 temporary address extensions
ipv6.ip6-privacy=2

#Disable captive portal checks
[connectivity]
enabled=false
